VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ENVIRONMENT_"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit
' ==========================================================================
' Class Name            : ENVIRONMENT_
' Module Type           : Class
' --------------------------------------------------------------------------
' Description           : This class is a container for methods dealing
'                                                 with Environments
' ==========================================================================

Public User As New ENVIRONMENT_User_Info
Public Path As New ENVIRONMENT_Sys_Paths
Public Comp As New ENVIRONMENT_Comp_Info

' //////////////////



